export const APP_CONTRACT = {
  baseURL: process.env.E2E_URL ?? 'http://localhost:3004',
  hasAuth: true,
  hasBilling: true,
  hasRoles: true,

  routes: {
    root: '/',
    login: '/login',
    billing: '/billing',
    dashboard: '/',
    checkout: '/billing',
    runs: '/runs',
  },

  testIds: {
    appRoot: 'app-root',
    heroHeading: 'hero-heading',
    featureCards: 'feature-cards',
    primaryList: 'primary-list',
    createPrimary: 'create-primary',
    searchPrimary: 'search-primary',
    createRunForm: 'create-run-form',
    runPromptInput: 'run-prompt-input',
    runItem: 'run-item',
    emptyState: 'empty-state',
    formError: 'form-error',
    successToast: 'success-toast',
    navUserMenu: 'nav-user-menu',
    logout: 'logout',
    loginLink: 'login-link',
    emailInput: 'email-input',
    passwordInput: 'password-input',
    passwordToggle: 'password-toggle',
    submitAuth: 'submit-auth',
    checkout: 'checkout',
    currentPlan: 'current-plan',
    limitWarning: 'limit-warning',
  },
}
