import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const root = path.resolve(__dirname, "..", "..");

const modulePagesDir = "app/modules";

export function generateModulePages(workspaceDir, modules) {
  const pagesRoot = path.join(workspaceDir, modulePagesDir);
  fs.mkdirSync(pagesRoot, { recursive: true });
  modules.forEach((m) => {
    const pagePath = path.join(pagesRoot, `${m.name}.tsx`);
    const content = `export default function Page() {
  return (
    <main style={{ padding: 24, fontFamily: "sans-serif" }}>
      <h2>${m.name} module</h2>
      <p>Version: ${m.version}</p>
      <p>Channel: ${m.channel}</p>
      <p>This page was auto-generated by DeNovo.</p>
    </main>
  );
}
`;
    fs.writeFileSync(pagePath, content);
  });
}

export function generateSqlBundle(runDir, modules) {
  const sqlDir = path.join(root, "services", "module-engine", "sql");
  const bundlePath = path.join(runDir, "artifacts", "schema.bundle.sql");
  const parts = [];
  modules.forEach((m) => {
    const file = path.join(sqlDir, `${m.name}.sql`);
    if (fs.existsSync(file)) {
      parts.push(fs.readFileSync(file, "utf8"));
    }
  });
  fs.mkdirSync(path.dirname(bundlePath), { recursive: true });
  fs.writeFileSync(bundlePath, parts.join("\n\n"));
  return bundlePath;
}
