import { exec } from "child_process";
import { promisify } from "util";
import { giteaClient } from "./gitea";
import { coolifyClient } from "./coolify";
import type { SlotMap } from "@/types/denovo";
import type { JobResult } from "./types";

const execAsync = promisify(exec);

export async function deployToGitea(
  workdir: string,
  slots: SlotMap,
  appId: string
): Promise<JobResult> {
  void appId; // reserved for future use

  const slug = slots.APP_NAME.toLowerCase().replace(/[^a-z0-9]+/g, "-");

  const repo = await giteaClient.createRepo({
    org: process.env.GITEA_APPS_ORG!,
    name: slug,
    description: `Generated by DeNovo — ${slots.APP_NAME}`,
    private: true,
  });

  const token = process.env.GITEA_API_TOKEN!;

  // workdir passed as cwd — not used in path.join/path.resolve
  await execAsync("git init", { cwd: workdir });
  await execAsync("git add .", { cwd: workdir });
  await execAsync(`git commit -m "feat: initial scaffold — ${slots.APP_NAME}"`, {
    cwd: workdir,
  });
  await execAsync(`git remote add origin "${repo.cloneUrl}"`, { cwd: workdir });
  await execAsync("git push -u origin main", {
    cwd: workdir,
    env: {
      ...process.env,
      GIT_ASKPASS: "echo",
      GIT_USERNAME: "denovo",
      GIT_PASSWORD: token,
    },
  });

  const app = await coolifyClient.createApplication({
    name: slots.APP_NAME,
    gitRepository: repo.cloneUrl,
    gitBranch: "main",
    port: 3000,
    domain: `https://${slug}.yourdomain.com`,
    environmentVariables: {
      NEXT_PUBLIC_APP_NAME: slots.APP_NAME,
      NEXT_PUBLIC_APP_URL: `https://${slug}.yourdomain.com`,
    },
  });

  await coolifyClient.deploy(app.id);

  return {
    type: "deploy",
    giteaUrl: repo.htmlUrl,
    coolifyAppId: app.id,
    domain: `${slug}.yourdomain.com`,
  };
}
