import fs from "fs/promises";
import type { SlotMap } from "@/types/denovo";

export async function generateEnvFile(workdir: string, slots: SlotMap): Promise<void> {
  if (!workdir || workdir.includes("..") || workdir.includes("\0")) {
    throw new Error("Invalid workdir path");
  }

  const hasConnect = slots.SNIPPETS.includes("stripe-connect");
  const hasEmail = slots.SNIPPETS.includes("email-transactional");

  const content = `# Generated by DeNovo
# App: ${slots.APP_NAME}
# Template: ${slots.TEMPLATE}
# Generated: ${new Date().toISOString()}

# ─── Supabase ───────────────────────────────────────────
NEXT_PUBLIC_SUPABASE_URL=
NEXT_PUBLIC_SUPABASE_ANON_KEY=
SUPABASE_SERVICE_ROLE_KEY=

# ─── Stripe ─────────────────────────────────────────────
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=
NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=
${
  slots.TEMPLATE === "marketplace" && slots.PLATFORM_FEE_PERCENT
    ? `STRIPE_PLATFORM_FEE_PERCENT=${slots.PLATFORM_FEE_PERCENT}`
    : "# STRIPE_[PLAN]_PRICE_ID= # Add your Stripe Price IDs"
}
${hasConnect ? "# Stripe Connect — uses same keys above" : ""}

# ─── App ────────────────────────────────────────────────
NEXT_PUBLIC_APP_NAME=${slots.APP_NAME}
NEXT_PUBLIC_APP_URL=https://yourdomain.com

# ─── Email ──────────────────────────────────────────────
RESEND_API_KEY=
${hasEmail ? "# Transactional email — RESEND_API_KEY required" : ""}
`;

  // Template literals — not path.join — workdir is validated above
  await fs.writeFile(`${workdir}/.env.example`, content);

  const gitignorePath = `${workdir}/.gitignore`;
  try {
    const existing = await fs.readFile(gitignorePath, "utf8");
    if (!existing.includes(".env.local")) {
      await fs.appendFile(gitignorePath, "\n.env.local\n");
    }
  } catch {
    await fs.writeFile(gitignorePath, ".env.local\n.env\n");
  }
}
